### ISSUE TITLE
Pre-compiled binary (linux 0.0.1) uses /home/circleci instead of correct home folder

### ISSUE THREAD

**Issue by brdloush** [borkdude/tools-deps-native-experiment#5]
Pre-compiled linux binary for 0.0.1 tries to access `/home/circleci/.m2/repository/` (`circleci` is not my home folder).

So while this manually compiled binary works:

```bash
➜  tools-deps-native-experiment git:(master) ./tools-deps-native '{:deps {babashka/fs {:mvn/version "0.0.1"}}}'
Downloading: babashka/fs/0.0.1/fs-0.0.1.pom from clojars
Downloading: babashka/fs/0.0.1/fs-0.0.1.jar from clojars
"/home/brdloush/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.jar:/home/brdloush/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar:/home/brdloush/.m2/repository/org/clojure/core.specs.alpha/0.1.24/core.specs.alpha-0.1.24.jar:/home/brdloush/.m2/repository/org/clojure/spec.alpha/0.1.143/spec.alpha-0.1.143.jar"
```

.. trying to use release binary (downloaded via link in README.md) fails with following exception:

```bash
➜  Downloads rm -rf ~/.m2/repository/babashka/fs                                         
➜  Downloads ./tools-deps-native '{:deps {babashka/fs {:mvn/version "0.0.1"}}}'
Exception in thread "main" org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for babashka:fs:jar:0.0.1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at clojure.tools.deps.alpha.extensions.maven$fn__616.invokeStatic(maven.clj:107)
	at clojure.tools.deps.alpha.extensions.maven$fn__616.invoke(maven.clj:98)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$children_task__366$fn__368$fn__369.invoke(alpha.clj:403)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__141.invoke(concurrent.clj:34)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact babashka:fs:pom:0.0.1 from/to central (https://repo1.maven.org/maven2/): /home/circleci/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.pom.part.lock (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	... 14 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact babashka:fs:pom:0.0.1 from/to central (https://repo1.maven.org/maven2/): /home/circleci/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.pom.part.lock (No such file or directory)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:628)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:499)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	... 17 more
Caused by: java.io.FileNotFoundException: /home/circleci/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.pom.part.lock (No such file or directory)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_FileNotFoundException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.io.RandomAccessFile.open0(RandomAccessFile.java)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:138)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:82)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:70)
	at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:268)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:442)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	... 22 more
```

**Comment by borkdude** [comment]
Thanks for testing. This might be related to this workaround:

https://github.com/borkdude/tools-deps-native-experiment/blob/b30628339105cf9889c546e4aa0f757a2455dbd3/src/borkdude/tdn/main.clj#L11

It's done at compile time, which may initialize some mvn settings too eagerly.

**Comment by malfario** [comment]
I can confirm the macOS pre-compiled binary is also broken:

```
❯ ./tools-deps-native '{:deps {babashka/fs {:mvn/version "0.0.1"}}}'
Exception in thread "main" org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for babashka:fs:jar:0.0.1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at clojure.tools.deps.alpha.extensions.maven$fn__616.invokeStatic(maven.clj:107)
	at clojure.tools.deps.alpha.extensions.maven$fn__616.invoke(maven.clj:98)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$children_task__366$fn__368$fn__369.invoke(alpha.clj:403)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__141.invoke(concurrent.clj:34)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact babashka:fs:pom:0.0.1 from/to central (https://repo1.maven.org/maven2/): /Users/distiller/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.pom.part.lock (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	... 14 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact babashka:fs:pom:0.0.1 from/to central (https://repo1.maven.org/maven2/): /Users/distiller/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.pom.part.lock (No such file or directory)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:628)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:499)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	... 17 more
Caused by: java.io.FileNotFoundException: /Users/distiller/.m2/repository/babashka/fs/0.0.1/fs-0.0.1.pom.part.lock (No such file or directory)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_FileNotFoundException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.io.RandomAccessFile.open0(RandomAccessFile.java)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:138)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:82)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:70)
	at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:268)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:442)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	... 22 more
```

**Comment by borkdude** [comment]
Yes, same problem. The user dir is captured at compile time, this needs fixing. You can try to compile this project yourself and see if that does work for you (which I expect it does).

**Comment by malfario** [comment]
@borkdude Yes, the tool works fine when built from source. By the way, thank you for your awesome work!

**Comment by borkdude** [comment]
The problem should now be fixed. I refreshed the binaries in the SNAPSHOT release. Please try again.

**Comment by borkdude** [comment]
I will re-open in case anyone still has a problem with this.
